### ISSUE TITLE
NWH Logo On Homepage 

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#12]
![nwh_logo_m](https://user-images.githubusercontent.com/23244213/31797893-864d707e-b4e5-11e7-9c17-994e4b7cc2f6.jpg)

**Comment by NWHarvest** [comment]
We will need to include the whole logo eventhough there is overlap with the colors on the navbar.

**Comment by alimon808** [comment]
With the current background, the blue part of your logo will not be visible or hard to see.
