### ISSUE TITLE
Enable Sorting for Listings 

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#25]
This may have to wait until the county field is added

**Comment by alimon808** [comment]
Sorting in mobile views?

**Comment by NWHarvest** [comment]
Yes, ideally members would be able to sort in mobile views so they can sift through listings more easily.

**Comment by NWHarvest** [comment]
Top 3 sorting fields: 
County
Zip Code
Type of Produce
