### ISSUE TITLE
Creating additional fields in Food Program Profiles

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#30]
Creating fields that allow food programs to include narrative about their program, and a "wish list" of popular produce within their food banks. 

Wish list could either be part of narrative, or could be separate section of profile.

**Comment by alimon808** [comment]
Purpose of the narrative?  Will this be visible to other users (e.g. food programs & growers)?

**Comment by NWHarvest** [comment]
Yes, the content will be available to other users. The narratives allow growers to become more familiar with the food banks in their communities (wants, needs, client preferences, etc.)

**Comment by alimon808** [comment]
Can you provide a sample narrative.

**Comment by NWHarvest** [comment]
[Produce Portal - Grower and Food Program Profile Pages.docx](https://github.com/openseattle/northwest-harvest-growing-connections/files/1488983/Produce.Portal.-.Grower.and.Food.Program.Profile.Pages.docx)

**Comment by alimon808** [comment]
dup #32, #37
