### ISSUE TITLE
Create Growers Home Page

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#31]
Landing page to be created that administrator can update, which includes relevant information to Growers

**Comment by NWHarvest** [comment]
[Produce Portal - Grower and Food Program Landing Pages.docx](https://github.com/openseattle/northwest-harvest-growing-connections/files/1488980/Produce.Portal.-.Grower.and.Food.Program.Landing.Pages.docx)

**Comment by alimon808** [comment]
Since this issue is for growers only, please create a new document that describe grower's home page requirements.  Add a section that contains sample information for each "relevant information to growers".

**Comment by NWHarvest** [comment]
Let me know if you'd like any additional information. [Produce Portal - Grower Home Page.docx](https://github.com/openseattle/northwest-harvest-growing-connections/files/1519574/Produce.Portal.-.Grower.Home.Page.docx)
