### ISSUE TITLE
Create Food Program Home Page 

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#32]
Landing page to be created that administrator can update, which includes relevant information to Food Programs.

**Comment by NWHarvest** [comment]
[Produce Portal - Grower and Food Program Landing Pages.docx](https://github.com/openseattle/northwest-harvest-growing-connections/files/1488982/Produce.Portal.-.Grower.and.Food.Program.Landing.Pages.docx)

**Comment by alimon808** [comment]
Since this issue is for food programs only, please create a new document that describe food program's home page requirements.  Add a section that contains sample information for each "relevant information to food programs".

**Comment by NWHarvest** [comment]
Let me know if you'd like any additonal information! 
[Produce Portal - Food Program Home Page.docx](https://github.com/openseattle/northwest-harvest-growing-connections/files/1519576/Produce.Portal.-.Food.Program.Home.Page.docx)
