### ISSUE TITLE
Food Program/ Grower Registration

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#39]
Is there a way for food programs to register to be a grower and a food program with one email address? Can we figure out a way to have food programs be able to access the grower side of the site with only one email?

**Comment by alimon808** [comment]
What does the food programs needs to be able to do that growers can?  Is it simply to have the ability to create a listing?

**Comment by NWHarvest** [comment]
Yes, that's correct, just the ability to create a listing.
