### ISSUE TITLE
Logout button on home screen

### ISSUE THREAD

**Issue by NWHarvest** [openseattle/northwest-harvest-growing-connections#71]
Is it possible to only have the logout button appear once users login to the site? It is a little confusing to have the logout button on the home screen if users aren't signed in yet.

**Comment by alimon808** [comment]
I'm unable to replicate this issue.  The button will only show if you are authenticated.  Are you logged in a separate tab?

**Comment by NWHarvest** [comment]
This might have been the case! I'm looking at this now again and I also cannot replicate it. I will close the issue, thanks Adrian!
