### ISSUE TITLE
Administrator User Profile page

### ISSUE THREAD

**Issue by alimon808** [openseattle/northwest-harvest-growing-connections#8]
### Manage Users
- disable / enable user

### Manage Listing
- delete listing

### Summary Report
- number of growers
- number of foodbanks
- number of listings ( per week)
- number of claimed listings (per week)

**Comment by NWHarvest** [comment]
Admin Page: 

Ability to view Growers Accounts, Food Program Accounts, and Avialable Produce. 
Ability to see all available produce, all claimed produce, and produce that is no longer available/ produce that has expired. 

**Please view Google Doc for additonal information.

**Comment by NWHarvest** [comment]
https://docs.google.com/document/d/1hu7Y2qdPZSw_eFvlN_UY1J30AT42bCXKBGL3OrOLD9c/edit?usp=sharing - Link to GoogleDoc

**Comment by alimon808** [comment]
create separate issue for number of listings and number of claimed listings per week statistics.
